name = "cf-bitswap-peer"
main = "./dist/worker.mjs"
compatibility_date = "2022-07-04"

[build]
command = "npm run build"

[env.alanshaw]
workers_dev = true
account_id = "4fe12d085474d33bdcfd8e9bed4d8f95"

[env.alanshaw.vars]
DEBUG = "true"
